apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: momo-frontend
  template:
    metadata:
      labels:
        app: momo-frontend
    spec:
      imagePullSecrets:
        - name: gitlab-regcred
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}/{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: momo-frontend
spec:
  selector:
    app: momo-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}