apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: momo-store
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: momo-backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: momo-frontend
                port:
                  number: {{ .Values.frontend.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: momo-store-tls