image:
  registry: gitlab.praktikum-services.ru:5050

backend:
  repository: std-033-40/momo-store/backend
  tag: "2089943"
  port: 8081
  replicas: 1

frontend:
  repository: std-033-40/momo-store/frontend
  tag: "2089943"
  port: 80
  replicas: 1

ingress:
  host: 158-160-151-41.nip.io
  className: nginx